apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
    - name: node
      image: node:20
      command: ["cat"]
      tty: true
    - name: docker
      image: docker:24-dind
      securityContext:
        privileged: true
    - name: kubectl
      image: bitnami/kubectl:1.30
      command: ["cat"]
      tty: true
    - name: tf
      image: hashicorp/terraform:1.9
      command: ["cat"]
      tty: true
