controller:
  admin:
    username: admin
    password: admin123
  serviceType: LoadBalancer

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest

  JCasC:
    enabled: true
    defaultConfig: true
    configScripts:
      kubernetes: |
        jenkins:
          clouds:
          - kubernetes:
              name: "kubernetes"
              serverUrl: "https://kubernetes.default"
              namespace: "jenkins"
              jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
              containerCapStr: "2"
              templates:
              - name: "default-agent"
                label: "k8s-agent"
                containers:
                - name: "jnlp"
                  image: "jenkins/inbound-agent:latest"
                  ttyEnabled: true
                  command: ""

persistence:
  enabled: true
  storageClass: gp3
  size: 20Gi

rbac:
  create: true

serviceAccount:
  create: true
  name: jenkins
