credentials:
  system:
    domainCredentials:
      - domain: "aws"
        credentials:
          - string:
              scope: GLOBAL
              id: "aws-creds"
              secret: "${AWS_SECRET_KEY}"
      - domain: "github"
        credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-creds"
              username: "${GITHUB_USER}"
              password: "${GITHUB_TOKEN}"
      - domain: "slack"
        credentials:
          - string:
              scope: GLOBAL
              id: "slack-token"
              secret: "${SLACK_TOKEN}"
