apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-canary
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
      track: canary
  template:
    metadata:
      labels:
        app: react-app
        track: canary
    spec:
      containers:
      - name: react-app
        image: docker.io/miusuario/cicdcompletelab-react:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
